In [4]:
import os
import pandas as pd
import numpy as np

In [5]:
%%time
df20191 = pd.read_csv("../../data/2019-1.csv", delimiter = "|")

FileNotFoundError: [Errno 2] No such file or directory: '../../data/2019-1.csv'

In [15]:
df20191.columns

Index(['TIPO_ID_APORTANTE', 'ID_APORTANTE', 'PLANILLA', 'COTIZANTES',
       'PERIODO_COTIZACION', 'PERIODO_SERVICIO', 'MODALIDAD', 'TIPO_APORTE',
       'TIPO_PLANILLA', 'FECHA_PAGO', 'VALOR_PLANILLA', 'COD_MUNICIPIO',
       'CLASE_APORTANTE', 'ACT_ECONOMICA'],
      dtype='object')

In [16]:
df20191

,TIPO_ID_APORTANTE,ID_APORTANTE,PLANILLA,COTIZANTES,PERIODO_COTIZACION,PERIODO_SERVICIO,MODALIDAD,TIPO_APORTE,TIPO_PLANILLA,FECHA_PAGO,VALOR_PLANILLA,COD_MUNICIPIO,CLASE_APORTANTE,ACT_ECONOMICA
0,NI,805011074,1017493516,458,201812,201901,ELECTRONICA,ACTIVO,E,2019-01-17 11:00:38,597857200,11001000,A,7490
1,NI,805011074,1017834993,1,201811,201812,ELECTRONICA,ACTIVO,N,2019-01-17 11:03:36,106600,11001000,A,7490
2,NI,805011074,1018937061,484,201901,201902,ELECTRONICA,ACTIVO,E,2019-02-15 11:43:21,734930500,11001000,A,7490
3,NI,805011074,1019701591,500,201902,201903,ELECTRONICA,ACTIVO,E,2019-03-14 11:18:31,459772100,11001000,A,7490
4,NI,805011074,1020258009,528,201903,201904,ELECTRONICA,ACTIVO,E,2019-04-12 13:54:27,867278266,11001000,A,7490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2457020,CC,1151937363,1022068425,1,201905,201905,ASISTIDA,ACTIVO,I,2019-06-28 13:54:08,244800,76001000,I,7490
2457021,CC,31579855,1021280966,1,201905,201905,ASISTIDA,ACTIVO,I,2019-05-22 16:33:50,236100,76001000,I,7490
2457022,CC,31640203,1018016165,1,201901,201901,ASISTIDA,ACTIVO,I,2019-01-09 16:38:07,232400,76111000,I,7490
2457023,CC,31640203,1018016943,1,201902,201902,ASISTIDA,ACTIVO,I,2019-03-13 15:10:37,240500,76111000,I,7490
2457024,CC,1143944385,1018992372,1,201902,201902,ASISTIDA,ACTIVO,I,2019-02-13 13:47:32,256300,76001000,I,7490

In [19]:
df20191.groupby("MODALIDAD").count().head()

,TIPO_ID_APORTANTE,ID_APORTANTE,PLANILLA,COTIZANTES,PERIODO_COTIZACION,PERIODO_SERVICIO,TIPO_APORTE,TIPO_PLANILLA,FECHA_PAGO,VALOR_PLANILLA,COD_MUNICIPIO,CLASE_APORTANTE,ACT_ECONOMICA
MODALIDAD,,,,,,,,,,,,,
ASISTIDA,1610565,1610565,1610565,1610565,1610565,1610565,1610565,1610565,1610565,1610565,1610565,1610565,1610565
ELECTRONICA,846460,846460,846460,846460,846460,846460,846460,846460,846460,846460,846460,846460,846460

In [6]:
%%time
df20192 = pd.read_csv("../data/2019-2.csv", delimiter = "|")

CPU times: user 3.29 s, sys: 509 ms, total: 3.8 s
Wall time: 3.81 s

In [7]:
df20192.columns

Index(['TIPO_ID_APORTANTE', 'ID_APORTANTE', 'PLANILLA', 'COTIZANTES',
       'PERIODO_COTIZACION', 'PERIODO_SERVICIO', 'MODALIDAD', 'TIPO_APORTE',
       'TIPO_PLANILLA', 'FECHA_PAGO', 'VALOR_PLANILLA', 'COD_MUNICIPIO',
       'CLASE_APORTANTE', 'ACT_ECONOMICA'],
      dtype='object')

In [8]:
df20192

,TIPO_ID_APORTANTE,ID_APORTANTE,PLANILLA,COTIZANTES,PERIODO_COTIZACION,PERIODO_SERVICIO,MODALIDAD,TIPO_APORTE,TIPO_PLANILLA,FECHA_PAGO,VALOR_PLANILLA,COD_MUNICIPIO,CLASE_APORTANTE,ACT_ECONOMICA
0,NI,805011074,1022450865,582,201906,201907,ELECTRONICA,ACTIVO,E,2019-07-15 13:56:43,561075200,11001000,A,7490
1,NI,805011074,1022523197,1,201904,201905,ELECTRONICA,ACTIVO,N,2019-07-15 13:59:27,93000,11001000,A,7490
2,NI,805011074,1022526131,1,201905,201906,ELECTRONICA,ACTIVO,N,2019-07-15 14:02:08,93000,11001000,A,7490
3,NI,805011074,1023014882,34,201305,201306,ELECTRONICA,ACTIVO,O,2019-10-28 10:45:57,4803600,11001000,A,7490
4,NI,805011074,1023015316,28,201306,201307,ELECTRONICA,ACTIVO,O,2019-10-28 10:45:57,3709400,11001000,A,7490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2650193,CC,3599597,1023041734,1,201908,201908,ELECTRONICA,ACTIVO,I,2019-08-07 11:49:59,103600,5001000,I,7490
2650194,CC,3599597,1023041786,1,201909,201909,ELECTRONICA,ACTIVO,I,2019-09-07 00:00:00,103600,5001000,I,7490
2650195,CC,3599597,1024444732,1,201910,201910,ELECTRONICA,ACTIVO,I,2019-10-05 00:00:00,103600,5001000,I,7490
2650196,CC,3599597,1025252516,1,201911,201911,ELECTRONICA,ACTIVO,I,2019-11-08 00:00:00,103600,5001000,I,7490
2650197,CC,3599597,1025850589,1,201912,201912,ELECTRONICA,ACTIVO,I,2019-12-07 00:00:00,103600,5001000,I,7490

In [20]:
%%time
df20201 = pd.read_csv("../data/2020-1.csv", delimiter = "|")

<string>:2: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.

CPU times: user 3.34 s, sys: 386 ms, total: 3.72 s
Wall time: 3.79 s

In [10]:
df20201.columns

Index(['TIPO_ID_APORTANTE', 'ID_APORTANTE', 'PLANILLA', 'COTIZANTES',
       'PERIODO_COTIZACION', 'PERIODO_SERVICIO', 'MODALIDAD', 'TIPO_APORTE',
       'TIPO_PLANILLA', 'FECHA_PAGO', 'VALOR_PLANILLA', 'COD_MUNICIPIO',
       'CLASE_APORTANTE', 'ACT_ECONOMICA'],
      dtype='object')

In [11]:
df20201

,TIPO_ID_APORTANTE,ID_APORTANTE,PLANILLA,COTIZANTES,PERIODO_COTIZACION,PERIODO_SERVICIO,MODALIDAD,TIPO_APORTE,TIPO_PLANILLA,FECHA_PAGO,VALOR_PLANILLA,COD_MUNICIPIO,CLASE_APORTANTE,ACT_ECONOMICA
0,NI,805011074,1026153323,1,201911,201912,ELECTRONICA,ACTIVO,N,2020-03-16 16:22:10,412500,11001000,A,7490
1,NI,805011074,1026705961,627,201912,202001,ELECTRONICA,ACTIVO,E,2020-01-16 13:51:07,640960900,11001000,A,7490
2,NI,2727586,1026379611,1,201912,202001,ELECTRONICA,ACTIVO,E,2020-01-03 00:00:00,203300,76111000,B,7490
3,NI,2727586,1027270543,1,202001,202002,ELECTRONICA,ACTIVO,E,2020-02-05 11:22:42,218000,76111000,B,7490
4,NI,2727586,1027928580,1,202002,202003,ELECTRONICA,ACTIVO,E,2020-03-02 15:38:21,218000,76111000,B,7490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2492690,CC,1143456065,1028690578,1,202001,202001,ASISTIDA,ACTIVO,I,2020-03-25 11:03:24,109800,8001000,I,9820
2492691,CC,43434583,1029142419,1,202004,202004,ASISTIDA,ACTIVO,I,2020-05-18 16:08:20,712500,5467000,I,9609
2492692,CC,43434583,1029924259,1,202005,202005,ASISTIDA,ACTIVO,I,2020-06-18 16:13:42,712500,5467000,I,9609
2492693,CC,79304320,1026765159,1,202001,202001,ELECTRONICA,ACTIVO,I,2020-01-14 11:03:15,5000,11001000,I,4921
2492694,CC,1075658160,1026764894,1,201908,201908,ELECTRONICA,ACTIVO,I,2020-01-14 10:55:13,108600,25899000,I,4792